### ISSUE TITLE
"Kommentare" als Standard-Anmeldefeld

### ISSUE THREAD

**Issue by JohaJung** [paul-goblin/mathebau-events#1]
Ein Freitextfeld (für Infos wie evtl verspätete Anreise/Allergien/etc.) ist in den meisten Fällen sinnvoll und ein Eventersteller sollte sich aktiv dagegen entscheiden müssen, es bei Anmeldung zu nutzen.

**Comment by paul-goblin** [comment]
Das Feld heist "Sonstige Anmerkungen", da "Kommentare" schon der Name für die Kommentarspalte der Admins ist
